[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "llzo-spherical-gb-workflow"
version = "0.1.0"
description = "Jobflow workflow for spherical LLZO grain-boundary construction and molecular dynamics"
readme = "README.md"
requires-python = ">=3.12,<3.13"
license = {file = "LICENSE"}
authors = [
  {name = "Ziyi Man"},
  {name = "Yaoshu Xie"},
  {name = "Zhanlin Li"},
  {name = "Lu Jiang"},
  {name = "Tingzheng Hou"}
]
keywords = ["LLZO", "grain boundaries", "molecular dynamics", "DeePMD", "Jobflow"]
classifiers = [
  "Development Status :: 3 - Alpha",
  "Intended Audience :: Science/Research",
  "License :: OSI Approved :: MIT License",
  "Programming Language :: Python :: 3.12",
  "Topic :: Scientific/Engineering :: Chemistry",
]
dependencies = [
  "numpy>=2.1,<2.2",
  "pandas>=2.3,<2.4",
  "pymatgen>=2025.10,<2026",
  "jobflow>=0.2.1,<0.3",
  "jobflow-remote>=0.1.8,<0.2",
  "qtoolkit>=0.1.6,<0.2",
  "scikit-optimize>=0.10.2,<0.11",
  "interfacemaster>=1.1.7,<1.2",
  "matplotlib>=3.10,<3.11",
  "PyYAML>=6.0"
]

[project.urls]
Repository = "https://github.com/mzy-67/LLZO-spherical-GB"
Issues = "https://github.com/mzy-67/LLZO-spherical-GB/issues"

[project.optional-dependencies]
test = ["pytest>=8"]

[tool.setuptools.packages.find]
where = ["src"]

[tool.pytest.ini_options]
pythonpath = ["src"]
testpaths = ["tests"]
